### PR TITLE
move authentication components from Cobuy to dogstack-agents

### PR DESCRIPTION
**Pull request by ahdinosaur**
corresponds with https://github.com/root-systems/dogstack/pull/77 and https://github.com/root-systems/cobuy/pull/180

### CODE REVIEW

**Review by iainkirkpatrick — APPROVED** [review]
awesome @ahdinosaur :D

**Review by iainkirkpatrick — APPROVED** [review]
🍎

**Comment by iainkirkpatrick** [comment]
oh i had already approved em!

**Comment by ahdinosaur** [comment]
published as 0.6! 🎉

**Pull request merged**
